In [13]:
import random
import numpy as np



a = np.random.randint(low=0, high=4, size=2)
a[0]

0

In [23]:
import math
categories = [2, 2, 2, 2, 2]
batch_size = 1
budget = 50
bestUpperBoundEstimate = 2 * budget / 3
gamma_list = [math.sqrt(C * math.log(C / batch_size) /
                        ((math.e - 1) * bestUpperBoundEstimate * batch_size))
              for C in categories]
# np.isnan(gamma_list)
# gamma_list

gamma = gamma_list[0]
p = 0.7333740550542971
# 0.9108275899694367
# 0.8252652349724254
# 0.7333740550542971

k = (p - gamma / 2) / (1 - gamma)

wc = k / (1 - k) 

wc
gamma_list
# categories[1]

[0.1555754826798944,
 0.1555754826798944,
 0.1555754826798944,
 0.1555754826798944,
 0.1555754826798944]

In [18]:
categories = [2, 2, 2, 2, 2]

[np.ones(C) for C in categories]

# np.array([1, 1])

[array([1., 1.]),
 array([1., 1.]),
 array([1., 1.]),
 array([1., 1.]),
 array([1., 1.])]

In [151]:
import pickle
file = open('../optimisation/data/init_data_voltage', 'rb')
data = pickle.load(file)
# print()

file.close()
# print(data)
np.std(data['y_init'])

0.9860141986807289

In [152]:
np.std([3.3, 15, 15, 15, 15, 15, 15,3.3,3.3,3.3,3.3,3.3])

5.85

In [281]:
import random
h = np.hstack([np.random.randint(0, C, 10)[:, None] for C in categories])
voltage = np.zeros(len(h))
for i in range (len(h)):
    
    a = list(h[i])
    circle = a.count(1)
    voltage[i] = (11 + circle * 0.6) -0.5 + np.random.random()
np.std(voltage)
np.mean(voltage)
# random.random()

12.121933882536947

In [284]:
a = 1e-10
a

1e-10